#!/bin/bash

set -e

# we should always set proper ownership before exiting, otherwise
# the created packages will have root:root ownership and we'll be unable
# to delete them from our host.
trap 'chown -R --reference /inside/build-package /out/' EXIT

# the source directory is mounted read-only to prevent issues where the build
# could alter the source; we should copy it somewhere inside the container
cp -a /source /tmp/build
cd /tmp/build

rm -rf build-dir
mkdir build-dir
cd build-dir
cmake -D CMAKE_INSTALL_PREFIX=/prod \
      -D CMAKE_BUILD_TYPE=Release \
      -G Ninja ..
ninja Core RealmConfig RealmImporter Realmd
ninja install

echo "ldconfig" > /tmp/post-ldconf
echo "echo >/dev/null" >> /tmp/post-ldconf

(
cd /out

fpm \
    -t deb \
    -s dir \
    -n librealm-dev \
    --license "Apache 2.0" \
    --version "${VERSION}" \
    --iteration "${ITERATION}" \
    --description "Realm is a mobile database: a replacement for Core Data & SQLite" \
    --url "https://realm.io" \
    --category "System Environment/Libraries" \
    --vendor "Realm" \
    --maintainer "Realm <help@realm.io>" \
    -d "libssl-dev" \
    -C "/prod" \
    /include=/usr \
    /lib/librealm.a=/usr/lib/librealm.a \
    /bin/realm-config=/usr/bin/realm-config

fpm \
    -t deb \
    -s dir \
    -n realm-utils \
    --license "Apache 2.0" \
    --version "${VERSION}" \
    --iteration "${ITERATION}" \
    --description "Realm is a mobile database: a replacement for Core Data & SQLite" \
    --url "https://realm.io" \
    --category "System Environment/Libraries" \
    --vendor "Realm" \
    --maintainer "Realm <help@realm.io>" \
    -d "libssl-dev" \
    -C "/prod" \
    /bin/realm-importer=/usr/bin/realm-importer
)

rm -rf -- * /prod/*
cmake -D CMAKE_INSTALL_PREFIX=/prod \
      -D CMAKE_BUILD_TYPE=Debug \
      -G Ninja ..
ninja Core RealmConfig RealmImporter Realmd
ninja install

cd /out

fpm \
    -t deb \
    -s dir \
    -n librealm-dev-dbg \
    --license "Apache 2.0" \
    --version "${VERSION}" \
    --iteration "${ITERATION}" \
    --description "Realm is a mobile database: a replacement for Core Data & SQLite" \
    --url "https://realm.io" \
    --category "System Environment/Libraries" \
    --vendor "Realm" \
    --maintainer "Realm <help@realm.io>" \
    -d "libssl-dev" \
    -C "/prod" \
    lib/librealm-dbg.a=/usr/lib/librealm-dbg.a
