#!/bin/bash

set -e

# we should always set proper ownership before exiting, otherwise
# the created packages will have root:root ownership and we'll be unable
# to delete them from our host.
trap 'chown -R --reference /inside/build-package /out/' EXIT

# the source directory is mounted read-only to prevent issues where the build
# could alter the source; we should copy it somewhere inside the container
cp -a /source /tmp/build
cd /tmp/build

rm -rf build-dir
mkdir build-dir
cd build-dir
cmake -DREALM_ENABLE_ENCRYPTION=1 \
      -DREALM_NO_TESTS=1 \
      -DCMAKE_INSTALL_PREFIX=/prod \
      -DCMAKE_BUILD_TYPE=Release \
      -GNinja ..
ninja
ninja install/strip
cpack -D CPACK_GENERATOR="DEB" -B /out -R "${VERSION}"
