#!/bin/bash

set -e

# we should always set proper ownership before exiting, otherwise
# the created packages will have root:root ownership and we'll be unable
# to delete them from our host.
trap 'chown -R --reference /inside/build-package /out/' EXIT

# the source directory is mounted read-only to prevent issues where the build
# could alter the source; we should copy it somewhere inside the container
cp -a /source /tmp/build
cd /tmp/build

rm -rf build-dir
mkdir build-dir
cd build-dir
cmake -DREALM_ENABLE_ENCRYPTION=1 \
      -DREALM_NO_TESTS=1 \
      -DCMAKE_INSTALL_PREFIX=/prod \
      -DCMAKE_BUILD_TYPE=Release \
      -GNinja ..
ninja
ninja install/strip

echo "ldconfig" > /tmp/post-ldconf
echo "echo >/dev/null" >> /tmp/post-ldconf

(
cd /out

fpm \
    -t deb \
    -s dir \
    -n librealm \
    --license "Apache 2.0" \
    --version "${VERSION}" \
    --iteration "${ITERATION}" \
    --description "Realm is a mobile database: a replacement for Core Data & SQLite" \
    --url "https://realm.io" \
    --category "System Environment/Libraries" \
    --vendor "Realm" \
    --maintainer "Realm <help@realm.io>" \
    --after-install "/tmp/post-ldconf" \
    --after-remove "/tmp/post-ldconf" \
    -d "libssl1.0.0" \
    -C "/prod" \
    lib/librealm.so=/usr/lib/librealm.so \
    lib/librealm-parser.so=/usr/lib/librealm-parser.so \
    libexec=/usr

fpm \
    -t deb \
    -s dir \
    -n librealm-dev \
    --license "Apache 2.0" \
    --version "${VERSION}" \
    --iteration "${ITERATION}" \
    --description "Realm is a mobile database: a replacement for Core Data & SQLite" \
    --url "https://realm.io" \
    --category "System Environment/Libraries" \
    --vendor "Realm" \
    --maintainer "Realm <help@realm.io>" \
    -d "librealm = ${VERSION}-${ITERATION}" \
    -d "libssl-dev" \
    -C "/prod" \
    /include=/usr \
    /lib/librealm.a=/usr/lib/librealm.a \
    /lib/librealm-parser.a=/usr/lib/librealm-parser.a \
    /bin/realm-config=/usr/bin/realm-config

#fpm \
#    -t deb \
#    -s dir \
#    -n realm-utils \
#    --license "Apache 2.0" \
#    --version "${VERSION}" \
#    --iteration "${ITERATION}" \
#    --description "Realm is a mobile database: a replacement for Core Data & SQLite" \
#    --url "https://realm.io" \
#    --category "System Environment/Libraries" \
#    --vendor "Realm" \
#    --maintainer "Realm <help@realm.io>" \
#    -d "librealm" \
#    -C "/prod" \
#    /bin/realm-importer=/usr/bin/realm-importer
)

rm -rf -- * /prod/*
cmake -DREALM_ENABLE_ENCRYPTION=1 \
      -DREALM_NO_TESTS=1 \
      -DCMAKE_INSTALL_PREFIX=/prod \
      -DCMAKE_BUILD_TYPE=Debug \
      -GNinja ..
ninja
ninja install

cd /out

fpm \
    -t deb \
    -s dir \
    -n librealm-dbg \
    --license "Apache 2.0" \
    --version "${VERSION}" \
    --iteration "${ITERATION}" \
    --description "Realm is a mobile database: a replacement for Core Data & SQLite" \
    --url "https://realm.io" \
    --category "System Environment/Libraries" \
    --vendor "Realm" \
    --maintainer "Realm <help@realm.io>" \
    --after-install "/tmp/post-ldconf" \
    --after-remove "/tmp/post-ldconf" \
    -d "libssl1.0.0" \
    -C "/prod" \
    lib/librealm-dbg.so=/usr/lib/librealm-dbg.so \
    lib/librealm-parser-dbg.so=/usr/lib/librealm-parser-dbg.so \
    libexec=/usr

fpm \
    -t deb \
    -s dir \
    -n librealm-dev-dbg \
    --license "Apache 2.0" \
    --version "${VERSION}" \
    --iteration "${ITERATION}" \
    --description "Realm is a mobile database: a replacement for Core Data & SQLite" \
    --url "https://realm.io" \
    --category "System Environment/Libraries" \
    --vendor "Realm" \
    --maintainer "Realm <help@realm.io>" \
    -d "librealm-dev = ${VERSION}-${ITERATION}" \
    -d "libssl-dev" \
    -C "/prod" \
    lib/librealm-dbg.a=/usr/lib/librealm-dbg.a \
    lib/librealm-parser-dbg.a=/usr/lib/librealm-parser-dbg.a
