CXXFLAGS_COMMON   = -Wall -Wextra -Werror -pedantic -Wno-long-long
CXXFLAGS_OPTIMIZE = -DNDEBUG -O3 -DUSE_SSE -msse4.2
CXXFLAGS_DEBUG    = -D_DEBUG -ggdb3 -DMAX_LIST_SIZE=4
CXXFLAGS_COVERAGE = -D_DEBUG -DMAX_LIST_SIZE=4 -DUSE_SSE -msse4.2
