Name:           libtightdb
Version:        0.1.5
Release:        1%{?dist}
Summary:        Fast, embedded database

License:        Closed Beta
URL:            http://www.tightdb.com
Source0:        libtightdb-%{version}.tar.gz
BuildRoot:      %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)

BuildRequires:  gcc-c++, chrpath
Requires:       glibc

# The tools (tightdbd and tightdb-import) depend on libtightdb.so
# and it must be excluded from the autogenerated list.
%global _privatelibs libtightdb[.]so.*
%global _privatelibs %{_privatelibs}|libtightdb-dbg[.]so.*
%global __provides_exclude ^(%{_privatelibs})$
%global __requires_exclude ^(%{_privatelibs})$


%description
Fast, embedded database

%package        devel
Summary:        Development files for %{name}
Requires:       %{name}%{?_isa} = %{version}-%{release}

%description    devel
The %{name}-devel package contains libraries and header files for
developing applications that use %{name}.


%prep
%setup -q


%build
sh ./build.sh config /usr
sh ./build.sh clean
sh ./build.sh build

%install
rm -rf $RPM_BUILD_ROOT
DESTDIR=$RPM_BUILD_ROOT sh build.sh install
chrpath --delete $RPM_BUILD_ROOT%{_libexecdir}/tightdbd-dbg
chrpath --delete $RPM_BUILD_ROOT%{_libexecdir}/tightdbd
chrpath --delete $RPM_BUILD_ROOT%{_bindir}/tightdb-import-dbg
chrpath --delete $RPM_BUILD_ROOT%{_bindir}/tightdb-import
chrpath --delete $RPM_BUILD_ROOT%{_bindir}/tightdb-config-dbg
chrpath --delete $RPM_BUILD_ROOT%{_bindir}/tightdb-config
find $RPM_BUILD_ROOT -name '*.la' -exec rm -f {} ';'

%clean
rm -rf $RPM_BUILD_ROOT

%post -p /sbin/ldconfig

%postun -p /sbin/ldconfig


%files
%defattr(-,root,root,-)
%doc README.md README.pdf
%{_libdir}/libtightdb.so
%{_libdir}/libtightdb-dbg.so.*
%{_libdir}/libtightdb-dbg.so
%{_libdir}/libtightdb.so.*
%{_libexecdir}/tightdbd
%{_libexecdir}/tightdbd-dbg
%{_bindir}/tightdb-import
%{_bindir}/tightdb-import-dbg

%files devel
%defattr(-,root,root,-)
%doc
%{_includedir}/*
%{_libdir}/*.a
%{_bindir}/tightdb-config
%{_bindir}/tightdb-config-dbg

%changelog
* Fri Jan  3 2014 Kenneth Geisshirt
- Tracking upstream release.
