# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.4

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.4.3/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.4.3/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/simon/code/realm-core

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/simon/code/realm-core

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.4.3/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.4.3/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/simon/code/realm-core/CMakeFiles /Users/simon/code/realm-core/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/simon/code/realm-core/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named realm

# Build rule for target.
realm: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 realm
.PHONY : realm

# fast build rule for target.
realm/fast:
	$(MAKE) -f src/realm/CMakeFiles/realm.dir/build.make src/realm/CMakeFiles/realm.dir/build
.PHONY : realm/fast

#=============================================================================
# Target rules for targets named realm-config

# Build rule for target.
realm-config: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 realm-config
.PHONY : realm-config

# fast build rule for target.
realm-config/fast:
	$(MAKE) -f src/realm/CMakeFiles/realm-config.dir/build.make src/realm/CMakeFiles/realm-config.dir/build
.PHONY : realm-config/fast

#=============================================================================
# Target rules for targets named realm-importer

# Build rule for target.
realm-importer: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 realm-importer
.PHONY : realm-importer

# fast build rule for target.
realm-importer/fast:
	$(MAKE) -f src/realm/CMakeFiles/realm-importer.dir/build.make src/realm/CMakeFiles/realm-importer.dir/build
.PHONY : realm-importer/fast

#=============================================================================
# Target rules for targets named realmd

# Build rule for target.
realmd: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 realmd
.PHONY : realmd

# fast build rule for target.
realmd/fast:
	$(MAKE) -f src/realm/CMakeFiles/realmd.dir/build.make src/realm/CMakeFiles/realmd.dir/build
.PHONY : realmd/fast

#=============================================================================
# Target rules for targets named realm-tests

# Build rule for target.
realm-tests: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 realm-tests
.PHONY : realm-tests

# fast build rule for target.
realm-tests/fast:
	$(MAKE) -f test/CMakeFiles/realm-tests.dir/build.make test/CMakeFiles/realm-tests.dir/build
.PHONY : realm-tests/fast

#=============================================================================
# Target rules for targets named test-util

# Build rule for target.
test-util: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test-util
.PHONY : test-util

# fast build rule for target.
test-util/fast:
	$(MAKE) -f test/util/CMakeFiles/test-util.dir/build.make test/util/CMakeFiles/test-util.dir/build
.PHONY : test-util/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... realm-config"
	@echo "... realm-importer"
	@echo "... realmd"
	@echo "... realm"
	@echo "... realm-tests"
	@echo "... test-util"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

