#!/bin/bash

set -e

# we should always set proper ownership before exiting, otherwise
# the created packages will have root:root ownership and we'll be unable
# to delete them from our host.
trap 'code=$?; chown -R --reference /inside/build-package /out/; exit $code' EXIT

name="realm-core-${VERSION}"

# If we're not releasing, append the iteration to the existing version
[ "$GIT_TAG" = "" ] && name="${name}-${ITERATION}"

# the source directory is mounted read-only to prevent issues where the build
# could alter the source; we should copy it somewhere inside the container
cp -a /source /tmp/build
cd /tmp/build

rm -rf build-dir
mkdir build-dir
cd build-dir
cmake -D CMAKE_INSTALL_PREFIX="/dest/${name}" \
      -D CMAKE_BUILD_TYPE=Release \
      -G Ninja ..
ninja Core RealmConfig RealmImporter Realmd
ninja install

rm -rf -- *
cmake -DCMAKE_INSTALL_PREFIX="/dest/${name}" \
      -DCMAKE_BUILD_TYPE=Debug \
      -GNinja ..
ninja Core RealmConfig RealmImporter Realmd
ninja install

cd /dest
mv "${name}/lib64" "${name}/lib"
tar -zcf "/out/${name}.tgz" "${name}"
