#!/bin/bash

set -e

# we should always set proper ownership before exiting, otherwise
# the created packages will have root:root ownership and we'll be unable
# to delete them from our host.
trap 'code=$?; chown -R --reference /inside/build-package /out/; exit $code' EXIT

name="realm-core-${VERSION}"

# the source directory is mounted read-only to prevent issues where the build
# could alter the source; we should copy it somewhere inside the container
cp -a /source /tmp/build
cd /tmp/build

# Configure the build
REALM_ENABLE_ENCRYPTION=yes sh build.sh config /
# Build and install
sh build.sh build
sh build.sh build-node
DESTDIR=/dest/${name} sh build.sh install-prod
DESTDIR=/dest/${name} sh build.sh install-devel
cp src/realm/librealm-node* /dest/${name}/lib

find /dest

cd /dest/${name}/lib
for file in *; do
  strip --strip-debug --strip-unneeded "$file"
done

cd /dest
tar -zcf /out/${name}.tgz ${name}
