#!/bin/bash

set -e

# we should always set proper ownership before exiting, otherwise
# the created packages will have root:root ownership and we'll be unable
# to delete them from our host.
trap 'chown -R --reference /inside/build-package /out/' EXIT

# the source directory is mounted read-only to prevent issues where the build
# could alter the source; we should copy it somewhere inside the container
cp -a /source /tmp/build
cd /tmp/build

rm -rf build-dir
mkdir build-dir
cd build-dir
cmake3 -DREALM_ENABLE_ENCRYPTION=1 \
      -DREALM_NO_TESTS=1 \
      -DCMAKE_INSTALL_PREFIX=/prod \
      -DCMAKE_BUILD_TYPE=Release \
      -GNinja ..
ninja
ninja install/strip

echo "ldconfig" > /tmp/post-ldconf
echo "echo >/dev/null" >> /tmp/post-ldconf

(
cd /out

fpm \
    -t rpm \
    -s dir \
    -n realm \
    --rpm-dist el6 \
    --license "Apache 2.0" \
    --version "${VERSION}" \
    --iteration "${ITERATION}" \
    --description "Realm is a mobile database: a replacement for Core Data & SQLite" \
    --url "https://realm.io" \
    --category "System Environment/Libraries" \
    --vendor "Realm" \
    --maintainer "Realm <help@realm.io>" \
    --after-install "/tmp/post-ldconf" \
    --after-remove "/tmp/post-ldconf" \
    -d "openssl" \
    -C "/prod" \
    lib64/librealm.so=/usr/lib64/librealm.so \
    libexec=/usr

fpm \
    -t rpm \
    -s dir \
    -n realm-devel \
    --rpm-dist el6 \
    --license "Apache 2.0" \
    --version "${VERSION}" \
    --iteration "${ITERATION}" \
    --description "Realm is a mobile database: a replacement for Core Data & SQLite" \
    --url "https://realm.io" \
    --category "System Environment/Libraries" \
    --vendor "Realm" \
    --maintainer "Realm <help@realm.io>" \
    -d "realm = ${VERSION}-${ITERATION}.el6" \
    -d "openssl-devel" \
    -C "/prod" \
    /include=/usr \
    /lib64/librealm.a=/usr/lib64/librealm.a \
    /bin/realm-config=/usr/bin/realm-config

fpm \
    -t rpm \
    -s dir \
    -n realm-utils \
    --rpm-dist el6 \
    --license "Apache 2.0" \
    --version "${VERSION}" \
    --iteration "${ITERATION}" \
    --description "Realm is a mobile database: a replacement for Core Data & SQLite" \
    --url "https://realm.io" \
    --category "System Environment/Libraries" \
    --vendor "Realm" \
    --maintainer "Realm <help@realm.io>" \
    -d "realm = ${VERSION}-${ITERATION}.el6" \
    -C "/prod" \
    /bin/realm-importer=/usr/bin/realm-importer
)


rm -rf -- * /prod/*
cmake3 -DREALM_ENABLE_ENCRYPTION=1 \
       -DREALM_NO_TESTS=1 \
       -DCMAKE_INSTALL_PREFIX=/prod \
       -DCMAKE_BUILD_TYPE=Debug \
       -GNinja ..
ninja
ninja install

cd /out

fpm \
    -t rpm \
    -s dir \
    -n realm-debug \
    --rpm-dist el6 \
    --license "Apache 2.0" \
    --version "${VERSION}" \
    --iteration "${ITERATION}" \
    --description "Realm is a mobile database: a replacement for Core Data & SQLite" \
    --url "https://realm.io" \
    --category "System Environment/Libraries" \
    --vendor "Realm" \
    --maintainer "Realm <help@realm.io>" \
    --after-install "/tmp/post-ldconf" \
    --after-remove "/tmp/post-ldconf" \
    -d "openssl" \
    -C "/prod" \
    lib64/librealm-dbg.so=/usr/lib64/librealm-dbg.so \
    libexec=/usr

fpm \
    -t rpm \
    -s dir \
    -n realm-devel-debug \
    --rpm-dist el6 \
    --license "Apache 2.0" \
    --version "${VERSION}" \
    --iteration "${ITERATION}" \
    --description "Realm is a mobile database: a replacement for Core Data & SQLite" \
    --url "https://realm.io" \
    --category "System Environment/Libraries" \
    --vendor "Realm" \
    --maintainer "Realm <help@realm.io>" \
    -d "realm-devel = ${VERSION}-${ITERATION}.el6" \
    -d "openssl-devel" \
    -C "/prod" \
    lib64/librealm-dbg.so=/usr/lib64/librealm-dbg.a
