#!/bin/bash -ex
# we should always set proper ownership before exiting, otherwise
# the created packages will have root:root ownership and we'll be unable
# to delete them from our host.
trap 'chown -R --reference /build-inside/build-package /out/' EXIT

clean_binaries() {
  # Remove unneeded information from binaries
  for path in $*; do
    cd "$path"

    rm -rf usr/{lib64,libexec,bin}/*-dbg*

    for file in usr/{lib64,libexec,bin}/*; do
        if [ -f "$file"  ];then
            strip --strip-debug --strip-unneeded "$file"
            chrpath -d "$file" || true
        fi
    done

    cd - >/dev/null
  done
}

# the source directory is mounted read-only to prevent issues where the build
# could alter the source; we should copy it somewhere inside the container
cp -a /source /tmp/build
cd /tmp/build

# Configure the build
REALM_ENABLE_ENCRYPTION=yes sh build.sh config /usr
# Build and install
sh build.sh build
sh build.sh build-node
DESTDIR=/prod sh build.sh install-prod
DESTDIR=/devel sh build.sh install-devel
cp src/realm/librealm-node* /devel/usr/lib64

clean_binaries /prod /devel

# Reorganise a few files
mkdir -p /utils/usr/bin
mv /prod/usr/bin/realm-import /utils/usr/bin
mv /prod/usr/lib64/*.so /devel/usr/lib64

echo "ldconfig" > /tmp/post-ldconf
echo "echo >/dev/null" >> /tmp/post-ldconf

cd /out

# don't forget to list all runtime dependencies for your package (i.e. all the
# shared libraries you link to!)
fpm \
    -t rpm \
    -s dir \
    -n realm \
    --rpm-dist el6 \
    --license "Realm License" \
    --version ${VERSION} \
    --iteration ${BUILD_NUMBER} \
    --description "Realm is a mobile database: a replacement for Core Data & SQLite" \
    --url "https://realm.io" \
    --category "System Environment/Libraries" \
    --vendor "Realm" \
    --maintainer "Realm <help@realm.io>" \
    --after-install /tmp/post-ldconf \
    --after-remove /tmp/post-ldconf \
    -d "openssl" \
    -C /prod \
    usr/lib64 usr/libexec

fpm \
    -t rpm \
    -s dir \
    -n realm-devel \
    --rpm-dist el6 \
    --license "Realm License" \
    --version ${VERSION} \
    --iteration ${BUILD_NUMBER} \
    --description "Development headers and tools for the realm-core C++ library" \
    --url "https://realm.io" \
    --category "System Environment/Libraries" \
    --vendor "Realm" \
    --maintainer "Realm <help@realm.io>" \
    -d "realm = ${VERSION}-${BUILD_NUMBER}.el6" \
    -d "openssl-devel" \
    -C /devel \
    usr/lib64 usr/include usr/bin

fpm \
    -t rpm \
    -s dir \
    -n realm-utils \
    --rpm-dist el6 \
    --license "Realm License" \
    --version ${VERSION} \
    --iteration ${BUILD_NUMBER} \
    --description "Utilities to work with Realm files" \
    --url "https://realm.io" \
    --category "Applications/Databases" \
    --vendor "Realm" \
    --maintainer "Realm <help@realm.io>" \
    -d "realm = ${VERSION}-${BUILD_NUMBER}.el6" \
    -C /utils \
    usr/bin
