set(CMAKE_EXE_LINKER_FLAGS_INIT "-L$ENV{HOMEBREW_PREFIX}/opt/llvm/lib/c++ -Wl,-rpath,$ENV{HOMEBREW_PREFIX}/opt/llvm/lib/c++")
set(CMAKE_SHARED_LINKER_FLAGS_INIT "-L$ENV{HOMEBREW_PREFIX}/opt/llvm/lib/c++ -Wl,-rpath,$ENV{HOMEBREW_PREFIX}/opt/llvm/lib/c++")
set(CMAKE_MODULE_LINKER_FLAGS_INIT "-L$ENV{HOMEBREW_PREFIX}/opt/llvm/lib/c++ -Wl,-rpath,$ENV{HOMEBREW_PREFIX}/opt/llvm/lib/c++")

set(CMAKE_AR $ENV{HOMEBREW_PREFIX}/opt/llvm/bin/llvm-ar)
set(CMAKE_ASM_COMPILER $ENV{HOMEBREW_PREFIX}/opt/llvm/bin/clang)
set(CMAKE_C_COMPILER $ENV{HOMEBREW_PREFIX}/opt/llvm/bin/clang)
set(CMAKE_CXX_COMPILER $ENV{HOMEBREW_PREFIX}/opt/llvm/bin/clang++)
set(CMAKE_LINKER $ENV{HOMEBREW_PREFIX}/opt/llvm/bin/lld)
set(CMAKE_NM $ENV{HOMEBREW_PREFIX}/opt/llvm/bin/llvm-nm)
set(CMAKE_OBJCOPY $ENV{HOMEBREW_PREFIX}/opt/llvm/bin/llvm-objcopy)
set(CMAKE_OBJDUMP $ENV{HOMEBREW_PREFIX}/opt/llvm/bin/llvm-objdump)
set(CMAKE_SIZE $ENV{HOMEBREW_PREFIX}/opt/llvm/bin/llvm-size)
set(CMAKE_STRIP $ENV{HOMEBREW_PREFIX}/opt/llvm/bin/llvm-strip)
