noinst_PROGRAMS = tutorial mini_tutorial

tutorial_SOURCES = tutorial.cpp
tutorial_CFLAGS = -DREALM_HAVE_CONFIG
tutorial_LDFLAGS =
tutorial_LIBS = ../src/tightdb/libtightdb.a

mini_tutorial_SOURCES = mini_tutorial.cpp
mini_tutorial_CFLAGS = -DREALM_HAVE_CONFIG
mini_tutorial_LDFLAGS =
mini_tutorial_LIBS = ../src/tightdb/libtightdb.a

include ../src/generic.mk
