#!/bin/bash

set -ex

# we should always set proper ownership before exiting, otherwise
# the created logs will have root:root ownership and we'll be unable
# to delete them from our host.
trap 'chown -R --reference /inside/test /test-logs/' EXIT

apt-get update
apt-get install -y /out/*.deb


# include build test here to ensure that everything is properly installed
packages=(librealm-dev librealm-dev-dbg realm-utils)

for x in "${packages[@]}"; do
  echo "--- querying $x ---"
  dpkg-query -s "$x"
done
