# NOTE: THIS SCRIPT IS SUPPOSED TO RUN IN A POSIX COMPATIBLE SHELL

source="$1"
target="$2"

get_config_param()
{
    local name line value
    name="$1"
    if ! line="$(grep "^$name:" "$source")"; then
        echo "ERROR: Failed to read configuration parameter '$name'" 1>&2
        return 1
    fi
    value="$(printf "%s\n" "$line" | cut -d: -f2-)" || return 1
    value="$(printf "%s\n" "$value" | sed 's/^ *//')" || return 1
    printf "%s\n" "$value"
}

cstring_escape()
{
    local str
    str="$1"
    str="$(printf "%s\n" "$str" | sed "s/\\([\"\\]\\)/\\\\\\1/g")" || return 1
    printf "%s\n" "$str"

}

install_bindir="$(get_config_param "install-bindir")" || exit 1
install_bindir_escaped="$(cstring_escape "$install_bindir")" || exit 1

cat >"$target" <<EOF
/*************************************************************************
 *
 * CAUTION:  DO NOT EDIT THIS FILE -- YOUR CHANGES WILL BE LOST!
 *
 * This file is generated by config.sh
 *
 *************************************************************************/

#define TIGHTDB_INSTALLATION_BIN_PATH "$install_bindir_escaped"
EOF
