noinst_PROGRAMS = table dyntable query view group sharedgroup

table_SOURCES = table.cpp
table_LDFLAGS =
table_LIBS = ../../src/tightdb/libtightdb.a

dyntable_SOURCES = dyntable.cpp
dyntable_LDFLAGS =
dyntable_LIBS = ../../src/tightdb/libtightdb.a

query_SOURCES = query.cpp
query_LDFLAGS =
query_LIBS = ../../src/tightdb/libtightdb.a

view_SOURCES = view.cpp
view_LDFLAGS =
view_LIBS = ../../src/tightdb/libtightdb.a

group_SOURCES = group.cpp
group_LDFLAGS =
group_LIBS = ../../src/tightdb/libtightdb.a

sharedgroup_SOURCES = sharedgroup.cpp
sharedgroup_LDFLAGS =
sharedgroup_LIBS = ../../src/tightdb/libtightdb.a

include ../../src/generic.mk
