FROM alanfranz/fwd-centos-7:latest
MAINTAINER Sebastian Lauwers <sl@realm.io>

# whatever is required for building should be installed in this image; just like BuildRequires: for RPM specs
RUN yum -y install python-cheetah which chrpath openssl-devel
