check_PROGRAMS = fuzzy-tests generate-fuzzy-input

fuzzy_tests_SOURCES = main.cpp
fuzzy_tests_LIBS = ../util/test-util.a

generate_fuzzy_input_SOURCES = generate.cpp
generate_fuzzy_input_LIBS = ../util/test-util.a

include ../../src/generic.mk
