#!/bin/bash

set -e

# we should always set proper ownership before exiting, otherwise
# the created logs will have root:root ownership and we'll be unable
# to delete them from our host.
trap 'code=$?; chown -R --reference /inside/test /test-logs/; exit $code' EXIT

touch /var/lib/rpm/*
yum install -y /out/*.rpm

# include build test here to ensure that everything is properly installed
packages=(realm realm-devel realm-utils realm-debug realm-devel-debug)

for x in "${packages[@]}"; do
  rpm -q "$x"
done
